image: bitnami/dotnet-sdk

stages:
    - build
    - test
    - deploy

build:
    stage: build
    script:
        - "dotnet build"
    artifacts:
      paths:
        - bin/

test:
    stage: test
    script: 
        - "dotnet test"
    artifacts:
      when: always
      paths:
        - ./**/*test-result.xml
      reports:
        junit:
          - ./**/*test-result.xml

deploy: 
    stage: deploy
    
    only:
        - dev
    artifacts:
        paths:
            - bin/release
        expire_in: 1 week
    script:
    # cd to where csproj is
    #- cd $deploy_path
    # publish the files - this will generate the publish files in bin/release 
    - dotnet publish -c Release -o ./publish dotnetcore.csproj

    # install zip and lftp
    - apt-get update -qq && apt-get install -y -qq zip lftp 
    # cd to bin
    - cd bin
    # zip release, name zip CreativelyCode.zip
    - mkdir prep
    - zip -r CreativelyCode
